/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *page1title;
    QGroupBox *groupBox;
    QRadioButton *queenRadio;
    QRadioButton *kingRadio;
    QSpinBox *nightsSpinBox;
    QGroupBox *groupBox_2;
    QRadioButton *standardRadio;
    QRadioButton *atriumRadio;
    QLineEdit *customerName;
    QDateEdit *dateEdit;
    QLabel *label_6;
    QSpinBox *childrenBox;
    QSpinBox *adultBox;
    QLabel *label_7;
    QLabel *label_8;
    QCheckBox *parkingCheckBox;
    QLabel *label_10;
    QLabel *priceLabel;
    QLabel *label_4;
    QLabel *label_12;
    QLabel *label_14;
    QFrame *line;
    QFrame *line_2;
    QLabel *label_16;
    QPushButton *nextPushButton;
    QFrame *line_3;
    QLabel *label_18;
    QFrame *line_7;
    QLabel *label_51;
    QLabel *label_2;
    QLabel *label;
    QWidget *page_3;
    QPushButton *backPushButton;
    QLineEdit *creditCardLineEdit;
    QLabel *label_5;
    QLabel *roomCostLabel;
    QLabel *label_11;
    QLabel *parkingLabel;
    QLabel *label_13;
    QLabel *taxLabel;
    QLabel *label_15;
    QLabel *resortLabel;
    QLabel *label_17;
    QLabel *totalCostLabel;
    QGroupBox *groupBox_3;
    QRadioButton *visaRadio;
    QRadioButton *masterCardRadio;
    QRadioButton *discoverRadio;
    QRadioButton *americaexpressRadio;
    QPushButton *payPushButton;
    QLineEdit *experationDateLineEdit;
    QLabel *page1title_2;
    QLabel *label_52;
    QLabel *label_53;
    QFrame *line_8;
    QLabel *label_54;
    QFrame *line_9;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *progress2;
    QWidget *page_2;
    QLabel *firstDayLabel;
    QLabel *numberOfNightsLabel;
    QLabel *roomTypeLabel;
    QLabel *parkingLabel_2;
    QLabel *guestsLabel;
    QLabel *totalCostLabel_2;
    QLabel *creditCardDigitsLabel;
    QPushButton *confirmPushButton;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *page1title_3;
    QLabel *label_57;
    QLabel *label_58;
    QFrame *line_10;
    QLabel *progress3;
    QLabel *label_3;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(798, 579);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 801, 531));
        QFont font;
        font.setFamily(QString::fromUtf8("Comic Sans MS"));
        font.setPointSize(14);
        stackedWidget->setFont(font);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        page1title = new QLabel(page);
        page1title->setObjectName(QString::fromUtf8("page1title"));
        page1title->setGeometry(QRect(10, 0, 791, 71));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Lust Display"));
        font1.setPointSize(36);
        font1.setBold(false);
        font1.setItalic(false);
        font1.setWeight(50);
        page1title->setFont(font1);
        page1title->setAutoFillBackground(false);
        page1title->setStyleSheet(QString::fromUtf8("border-image: url(:/beach.jpg) 0 0 0 0 stretch stretch;\n"
"color: rgb(49, 95, 105);"));
        page1title->setAlignment(Qt::AlignCenter);
        groupBox = new QGroupBox(page);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(50, 240, 261, 61));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Gill Sans"));
        font2.setPointSize(16);
        groupBox->setFont(font2);
        groupBox->setLayoutDirection(Qt::LeftToRight);
        queenRadio = new QRadioButton(groupBox);
        queenRadio->setObjectName(QString::fromUtf8("queenRadio"));
        queenRadio->setGeometry(QRect(10, 30, 101, 20));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Gill Sans"));
        font3.setPointSize(13);
        queenRadio->setFont(font3);
        queenRadio->setChecked(true);
        kingRadio = new QRadioButton(groupBox);
        kingRadio->setObjectName(QString::fromUtf8("kingRadio"));
        kingRadio->setGeometry(QRect(120, 30, 131, 20));
        kingRadio->setFont(font3);
        nightsSpinBox = new QSpinBox(page);
        nightsSpinBox->setObjectName(QString::fromUtf8("nightsSpinBox"));
        nightsSpinBox->setGeometry(QRect(490, 380, 41, 21));
        nightsSpinBox->setFont(font3);
        nightsSpinBox->setMinimum(1);
        nightsSpinBox->setMaximum(7);
        groupBox_2 = new QGroupBox(page);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(380, 240, 261, 61));
        groupBox_2->setFont(font2);
        groupBox_2->setLayoutDirection(Qt::LeftToRight);
        standardRadio = new QRadioButton(groupBox_2);
        standardRadio->setObjectName(QString::fromUtf8("standardRadio"));
        standardRadio->setGeometry(QRect(10, 30, 141, 20));
        standardRadio->setFont(font3);
        standardRadio->setChecked(true);
        atriumRadio = new QRadioButton(groupBox_2);
        atriumRadio->setObjectName(QString::fromUtf8("atriumRadio"));
        atriumRadio->setGeometry(QRect(100, 30, 141, 21));
        atriumRadio->setFont(font3);
        customerName = new QLineEdit(page);
        customerName->setObjectName(QString::fromUtf8("customerName"));
        customerName->setGeometry(QRect(110, 140, 201, 21));
        customerName->setFont(font3);
        dateEdit = new QDateEdit(page);
        dateEdit->setObjectName(QString::fromUtf8("dateEdit"));
        dateEdit->setGeometry(QRect(180, 381, 131, 21));
        dateEdit->setFont(font3);
        label_6 = new QLabel(page);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(50, 380, 131, 21));
        label_6->setFont(font2);
        childrenBox = new QSpinBox(page);
        childrenBox->setObjectName(QString::fromUtf8("childrenBox"));
        childrenBox->setGeometry(QRect(730, 141, 41, 21));
        childrenBox->setFont(font3);
        childrenBox->setMaximum(3);
        adultBox = new QSpinBox(page);
        adultBox->setObjectName(QString::fromUtf8("adultBox"));
        adultBox->setGeometry(QRect(480, 141, 41, 21));
        adultBox->setFont(font3);
        adultBox->setMinimum(1);
        adultBox->setMaximum(4);
        label_7 = new QLabel(page);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(390, 140, 81, 21));
        label_7->setFont(font2);
        label_8 = new QLabel(page);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(660, 140, 61, 21));
        label_8->setFont(font2);
        parkingCheckBox = new QCheckBox(page);
        parkingCheckBox->setObjectName(QString::fromUtf8("parkingCheckBox"));
        parkingCheckBox->setGeometry(QRect(650, 270, 91, 20));
        parkingCheckBox->setFont(font2);
        parkingCheckBox->setLayoutDirection(Qt::RightToLeft);
        label_10 = new QLabel(page);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(50, 470, 141, 21));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Gill Sans"));
        font4.setPointSize(16);
        font4.setBold(false);
        font4.setWeight(50);
        label_10->setFont(font4);
        priceLabel = new QLabel(page);
        priceLabel->setObjectName(QString::fromUtf8("priceLabel"));
        priceLabel->setGeometry(QRect(180, 470, 71, 21));
        priceLabel->setFont(font3);
        priceLabel->setFrameShape(QFrame::NoFrame);
        label_4 = new QLabel(page);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(390, 380, 91, 21));
        label_4->setFont(font2);
        label_12 = new QLabel(page);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(50, 140, 59, 16));
        label_12->setFont(font2);
        label_14 = new QLabel(page);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(30, 90, 151, 20));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Lust"));
        font5.setPointSize(18);
        label_14->setFont(font5);
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(49, 95, 105);"));
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line = new QFrame(page);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(110, 90, 671, 20));
        line->setStyleSheet(QString::fromUtf8(""));
        line->setLineWidth(1);
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(page);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(100, 200, 681, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_16 = new QLabel(page);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(30, 200, 411, 20));
        label_16->setFont(font5);
        label_16->setStyleSheet(QString::fromUtf8("color: rgb(49, 95, 105);"));
        label_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        nextPushButton = new QPushButton(page);
        nextPushButton->setObjectName(QString::fromUtf8("nextPushButton"));
        nextPushButton->setGeometry(QRect(672, 470, 101, 31));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Lust"));
        font6.setPointSize(18);
        font6.setBold(false);
        font6.setWeight(50);
        nextPushButton->setFont(font6);
        nextPushButton->setAutoFillBackground(false);
        nextPushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(49, 95, 105);"));
        line_3 = new QFrame(page);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(100, 340, 681, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_18 = new QLabel(page);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(30, 340, 271, 20));
        label_18->setFont(font5);
        label_18->setStyleSheet(QString::fromUtf8("color: rgb(49, 95, 105);"));
        label_18->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line_7 = new QFrame(page);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(90, 430, 691, 20));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        label_51 = new QLabel(page);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(30, 430, 151, 20));
        label_51->setFont(font5);
        label_51->setStyleSheet(QString::fromUtf8("color: rgb(49, 95, 105);"));
        label_51->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_2 = new QLabel(page);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(7, 55, 791, 511));
        label_2->setStyleSheet(QString::fromUtf8("background-color: rgb(232, 214, 183);\n"
""));
        label = new QLabel(page);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 500, 301, 20));
        label->setStyleSheet(QString::fromUtf8("background-color: rgb(49, 95, 105);"));
        stackedWidget->addWidget(page);
        label_2->raise();
        page1title->raise();
        groupBox->raise();
        nightsSpinBox->raise();
        groupBox_2->raise();
        customerName->raise();
        dateEdit->raise();
        label_6->raise();
        childrenBox->raise();
        adultBox->raise();
        label_7->raise();
        label_8->raise();
        parkingCheckBox->raise();
        label_10->raise();
        priceLabel->raise();
        label_4->raise();
        label_12->raise();
        label_14->raise();
        line->raise();
        line_2->raise();
        label_16->raise();
        nextPushButton->raise();
        line_3->raise();
        label_18->raise();
        line_7->raise();
        label_51->raise();
        label->raise();
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        backPushButton = new QPushButton(page_3);
        backPushButton->setObjectName(QString::fromUtf8("backPushButton"));
        backPushButton->setGeometry(QRect(40, 370, 113, 32));
        backPushButton->setFont(font6);
        backPushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(49, 95, 105);"));
        creditCardLineEdit = new QLineEdit(page_3);
        creditCardLineEdit->setObjectName(QString::fromUtf8("creditCardLineEdit"));
        creditCardLineEdit->setGeometry(QRect(580, 280, 161, 21));
        creditCardLineEdit->setFont(font3);
        label_5 = new QLabel(page_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(40, 130, 61, 21));
        label_5->setFont(font2);
        roomCostLabel = new QLabel(page_3);
        roomCostLabel->setObjectName(QString::fromUtf8("roomCostLabel"));
        roomCostLabel->setGeometry(QRect(100, 130, 59, 21));
        roomCostLabel->setFont(font3);
        label_11 = new QLabel(page_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(40, 170, 59, 21));
        label_11->setFont(font2);
        parkingLabel = new QLabel(page_3);
        parkingLabel->setObjectName(QString::fromUtf8("parkingLabel"));
        parkingLabel->setGeometry(QRect(100, 170, 59, 21));
        parkingLabel->setFont(font3);
        label_13 = new QLabel(page_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(240, 130, 59, 21));
        label_13->setFont(font2);
        taxLabel = new QLabel(page_3);
        taxLabel->setObjectName(QString::fromUtf8("taxLabel"));
        taxLabel->setGeometry(QRect(300, 130, 59, 21));
        taxLabel->setFont(font3);
        label_15 = new QLabel(page_3);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(240, 170, 59, 21));
        label_15->setFont(font2);
        resortLabel = new QLabel(page_3);
        resortLabel->setObjectName(QString::fromUtf8("resortLabel"));
        resortLabel->setGeometry(QRect(300, 170, 59, 21));
        resortLabel->setFont(font3);
        label_17 = new QLabel(page_3);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(620, 180, 59, 21));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Gill Sans"));
        font7.setPointSize(16);
        font7.setBold(true);
        font7.setWeight(75);
        label_17->setFont(font7);
        totalCostLabel = new QLabel(page_3);
        totalCostLabel->setObjectName(QString::fromUtf8("totalCostLabel"));
        totalCostLabel->setGeometry(QRect(680, 180, 59, 21));
        totalCostLabel->setFont(font3);
        groupBox_3 = new QGroupBox(page_3);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(40, 260, 351, 81));
        groupBox_3->setFont(font2);
        visaRadio = new QRadioButton(groupBox_3);
        visaRadio->setObjectName(QString::fromUtf8("visaRadio"));
        visaRadio->setGeometry(QRect(10, 30, 100, 20));
        visaRadio->setFont(font3);
        visaRadio->setChecked(true);
        masterCardRadio = new QRadioButton(groupBox_3);
        masterCardRadio->setObjectName(QString::fromUtf8("masterCardRadio"));
        masterCardRadio->setGeometry(QRect(10, 50, 100, 20));
        masterCardRadio->setFont(font3);
        discoverRadio = new QRadioButton(groupBox_3);
        discoverRadio->setObjectName(QString::fromUtf8("discoverRadio"));
        discoverRadio->setGeometry(QRect(190, 30, 100, 20));
        discoverRadio->setFont(font3);
        americaexpressRadio = new QRadioButton(groupBox_3);
        americaexpressRadio->setObjectName(QString::fromUtf8("americaexpressRadio"));
        americaexpressRadio->setGeometry(QRect(190, 50, 141, 20));
        americaexpressRadio->setFont(font3);
        payPushButton = new QPushButton(page_3);
        payPushButton->setObjectName(QString::fromUtf8("payPushButton"));
        payPushButton->setGeometry(QRect(630, 370, 113, 31));
        payPushButton->setFont(font6);
        payPushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(49, 95, 105);"));
        experationDateLineEdit = new QLineEdit(page_3);
        experationDateLineEdit->setObjectName(QString::fromUtf8("experationDateLineEdit"));
        experationDateLineEdit->setGeometry(QRect(580, 310, 161, 21));
        experationDateLineEdit->setFont(font3);
        page1title_2 = new QLabel(page_3);
        page1title_2->setObjectName(QString::fromUtf8("page1title_2"));
        page1title_2->setGeometry(QRect(0, 0, 791, 71));
        page1title_2->setFont(font1);
        page1title_2->setAutoFillBackground(false);
        page1title_2->setStyleSheet(QString::fromUtf8("border-image: url(:/sand.jpg) 0 0 0 0 stretch stretch;\n"
"color: rgb(49, 95, 105);"));
        page1title_2->setAlignment(Qt::AlignCenter);
        label_52 = new QLabel(page_3);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(0, 70, 791, 371));
        label_52->setStyleSheet(QString::fromUtf8("background-color: rgb(232, 214, 183);\n"
""));
        label_53 = new QLabel(page_3);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(20, 90, 151, 20));
        label_53->setFont(font5);
        label_53->setStyleSheet(QString::fromUtf8("color: rgb(49, 95, 105);"));
        label_53->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line_8 = new QFrame(page_3);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(80, 90, 691, 20));
        line_8->setStyleSheet(QString::fromUtf8(""));
        line_8->setLineWidth(1);
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        label_54 = new QLabel(page_3);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(20, 220, 151, 20));
        label_54->setFont(font5);
        label_54->setStyleSheet(QString::fromUtf8("color: rgb(49, 95, 105);"));
        label_54->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line_9 = new QFrame(page_3);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(130, 220, 651, 20));
        line_9->setStyleSheet(QString::fromUtf8(""));
        line_9->setLineWidth(1);
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        label_55 = new QLabel(page_3);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(500, 280, 101, 21));
        label_55->setFont(font2);
        label_56 = new QLabel(page_3);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(500, 310, 101, 21));
        label_56->setFont(font2);
        progress2 = new QLabel(page_3);
        progress2->setObjectName(QString::fromUtf8("progress2"));
        progress2->setGeometry(QRect(0, 410, 501, 20));
        progress2->setStyleSheet(QString::fromUtf8("background-color: rgb(49, 95, 105);"));
        stackedWidget->addWidget(page_3);
        label_52->raise();
        backPushButton->raise();
        creditCardLineEdit->raise();
        label_5->raise();
        roomCostLabel->raise();
        label_11->raise();
        parkingLabel->raise();
        label_13->raise();
        taxLabel->raise();
        label_15->raise();
        resortLabel->raise();
        label_17->raise();
        totalCostLabel->raise();
        groupBox_3->raise();
        payPushButton->raise();
        experationDateLineEdit->raise();
        page1title_2->raise();
        label_53->raise();
        line_8->raise();
        label_54->raise();
        line_9->raise();
        label_55->raise();
        label_56->raise();
        progress2->raise();
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        firstDayLabel = new QLabel(page_2);
        firstDayLabel->setObjectName(QString::fromUtf8("firstDayLabel"));
        firstDayLabel->setGeometry(QRect(700, 130, 101, 21));
        QFont font8;
        font8.setFamily(QString::fromUtf8("Gill Sans"));
        firstDayLabel->setFont(font8);
        numberOfNightsLabel = new QLabel(page_2);
        numberOfNightsLabel->setObjectName(QString::fromUtf8("numberOfNightsLabel"));
        numberOfNightsLabel->setGeometry(QRect(160, 130, 91, 21));
        numberOfNightsLabel->setFont(font8);
        roomTypeLabel = new QLabel(page_2);
        roomTypeLabel->setObjectName(QString::fromUtf8("roomTypeLabel"));
        roomTypeLabel->setGeometry(QRect(160, 180, 121, 21));
        roomTypeLabel->setFont(font8);
        parkingLabel_2 = new QLabel(page_2);
        parkingLabel_2->setObjectName(QString::fromUtf8("parkingLabel_2"));
        parkingLabel_2->setGeometry(QRect(400, 130, 59, 21));
        parkingLabel_2->setFont(font8);
        guestsLabel = new QLabel(page_2);
        guestsLabel->setObjectName(QString::fromUtf8("guestsLabel"));
        guestsLabel->setGeometry(QRect(400, 180, 141, 21));
        guestsLabel->setFont(font8);
        totalCostLabel_2 = new QLabel(page_2);
        totalCostLabel_2->setObjectName(QString::fromUtf8("totalCostLabel_2"));
        totalCostLabel_2->setGeometry(QRect(700, 230, 59, 21));
        totalCostLabel_2->setFont(font8);
        creditCardDigitsLabel = new QLabel(page_2);
        creditCardDigitsLabel->setObjectName(QString::fromUtf8("creditCardDigitsLabel"));
        creditCardDigitsLabel->setGeometry(QRect(700, 180, 101, 21));
        creditCardDigitsLabel->setFont(font8);
        confirmPushButton = new QPushButton(page_2);
        confirmPushButton->setObjectName(QString::fromUtf8("confirmPushButton"));
        confirmPushButton->setGeometry(QRect(650, 290, 113, 32));
        confirmPushButton->setFont(font5);
        confirmPushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(49, 95, 105);"));
        label_22 = new QLabel(page_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(570, 130, 121, 16));
        label_22->setFont(font2);
        label_23 = new QLabel(page_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(60, 130, 91, 20));
        label_23->setFont(font2);
        label_24 = new QLabel(page_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(60, 180, 81, 16));
        label_24->setFont(font2);
        label_25 = new QLabel(page_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(330, 130, 61, 21));
        label_25->setFont(font2);
        label_26 = new QLabel(page_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(330, 180, 51, 21));
        label_26->setFont(font2);
        label_27 = new QLabel(page_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(630, 230, 51, 21));
        label_27->setFont(font7);
        label_27->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_28 = new QLabel(page_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(580, 180, 121, 21));
        label_28->setFont(font2);
        page1title_3 = new QLabel(page_2);
        page1title_3->setObjectName(QString::fromUtf8("page1title_3"));
        page1title_3->setGeometry(QRect(0, 0, 791, 71));
        page1title_3->setFont(font1);
        page1title_3->setAutoFillBackground(false);
        page1title_3->setStyleSheet(QString::fromUtf8("border-image: url(:/sky.jpg) 0 0 0 0 stretch stretch;\n"
"color: rgb(49, 95, 105);"));
        page1title_3->setAlignment(Qt::AlignCenter);
        label_57 = new QLabel(page_2);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(0, 70, 791, 291));
        label_57->setStyleSheet(QString::fromUtf8("background-color: rgb(232, 214, 183);\n"
""));
        label_58 = new QLabel(page_2);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(30, 90, 151, 20));
        label_58->setFont(font5);
        label_58->setStyleSheet(QString::fromUtf8("color: rgb(49, 95, 105);"));
        label_58->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line_10 = new QFrame(page_2);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(170, 90, 611, 20));
        line_10->setStyleSheet(QString::fromUtf8(""));
        line_10->setLineWidth(1);
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        progress3 = new QLabel(page_2);
        progress3->setObjectName(QString::fromUtf8("progress3"));
        progress3->setGeometry(QRect(0, 330, 791, 20));
        progress3->setStyleSheet(QString::fromUtf8("background-color: rgb(49, 95, 105);"));
        label_3 = new QLabel(page_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(-70, 220, 401, 171));
        label_3->setStyleSheet(QString::fromUtf8("border-image: url(:/palm.png) 0 0 0 0 stretch stretch;"));
        stackedWidget->addWidget(page_2);
        label_57->raise();
        firstDayLabel->raise();
        numberOfNightsLabel->raise();
        roomTypeLabel->raise();
        parkingLabel_2->raise();
        guestsLabel->raise();
        totalCostLabel_2->raise();
        creditCardDigitsLabel->raise();
        confirmPushButton->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        page1title_3->raise();
        label_58->raise();
        line_10->raise();
        progress3->raise();
        label_3->raise();
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 798, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(0);
        payPushButton->setDefault(false);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        page1title->setText(QApplication::translate("MainWindow", "Canal Resort", nullptr));
        groupBox->setTitle(QApplication::translate("MainWindow", "Room Type:", nullptr));
        queenRadio->setText(QApplication::translate("MainWindow", "2 Queen Beds", nullptr));
        kingRadio->setText(QApplication::translate("MainWindow", "1 King Bed", nullptr));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Room View:", nullptr));
        standardRadio->setText(QApplication::translate("MainWindow", "Standard", nullptr));
        atriumRadio->setText(QApplication::translate("MainWindow", "Atrium", nullptr));
        dateEdit->setDisplayFormat(QApplication::translate("MainWindow", "MM/dd/yyyy", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "First Day of Stay:", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Adults 18+:", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Children: ", nullptr));
        parkingCheckBox->setText(QApplication::translate("MainWindow", "Parking:   ", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Estimated total: ", nullptr));
        priceLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Total Nights:", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "Name:", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "People", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Room", nullptr));
        nextPushButton->setText(QApplication::translate("MainWindow", "Next", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Dates", nullptr));
        label_51->setText(QApplication::translate("MainWindow", "Cost", nullptr));
        label_2->setText(QString());
        label->setText(QString());
        backPushButton->setText(QApplication::translate("MainWindow", "Back", nullptr));
        creditCardLineEdit->setText(QString());
        label_5->setText(QApplication::translate("MainWindow", "Room:", nullptr));
        roomCostLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Parking: ", nullptr));
        parkingLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "Tax:", nullptr));
        taxLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "Resort:", nullptr));
        resortLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Total:", nullptr));
        totalCostLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Card Type", nullptr));
        visaRadio->setText(QApplication::translate("MainWindow", "VISA", nullptr));
        masterCardRadio->setText(QApplication::translate("MainWindow", "MasterCard", nullptr));
        discoverRadio->setText(QApplication::translate("MainWindow", "Discover", nullptr));
        americaexpressRadio->setText(QApplication::translate("MainWindow", "American Express", nullptr));
        payPushButton->setText(QApplication::translate("MainWindow", "Pay", nullptr));
        experationDateLineEdit->setInputMask(QApplication::translate("MainWindow", "99/99", nullptr));
        experationDateLineEdit->setText(QApplication::translate("MainWindow", "01/20", nullptr));
        page1title_2->setText(QApplication::translate("MainWindow", "Canal Resort", nullptr));
        label_52->setText(QString());
        label_53->setText(QApplication::translate("MainWindow", "Cost", nullptr));
        label_54->setText(QApplication::translate("MainWindow", "Payment", nullptr));
        label_55->setText(QApplication::translate("MainWindow", "Number:", nullptr));
        label_56->setText(QApplication::translate("MainWindow", "Expiration:", nullptr));
        progress2->setText(QString());
        firstDayLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        numberOfNightsLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        roomTypeLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        parkingLabel_2->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        guestsLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        totalCostLabel_2->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        creditCardDigitsLabel->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        confirmPushButton->setText(QApplication::translate("MainWindow", "Done", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "First Day of Stay:", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Total Nights:", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Room Type: ", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "Parking:", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "Guests:", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "Total:", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "Card Ending In:", nullptr));
        page1title_3->setText(QApplication::translate("MainWindow", "Canal Resort", nullptr));
        label_57->setText(QString());
        label_58->setText(QApplication::translate("MainWindow", "Confirmation", nullptr));
        progress3->setText(QString());
        label_3->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
